message: Greetings from the PRODUCT-QUERY-SIDE microservice [using the PRODUCTION config].

management:
    security:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
axon:
    amqp:
        exchange: product.events.fanout.exchange
        transaction-mode: transactional
        queue: event.stream
    serializer:
        general: jackson
    eventhandling:
        processors:
            productQuery:
                mode: tracking
                source: myQueueMessageSource
spring:
    application:
#        exchange: product.events.fanout.exchange
        databaseName: sagas
        queue: event.stream
        # terminal: product.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
       mongodb:
          uri: mongodb://mongodb:27017/sagas
       rest:
            #base-path: api/v1
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: DEBUG
        com.soagrowers: DEBUG
    file: ./logs/query-side-server.log